apiVersion: apps/v1
kind: Deployment
metadata:
  name: usedmarket-backend
  namespace: suho
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: usedmarket-backend
  template:
    metadata:
      labels:
        app: usedmarket-backend
    spec:
      containers:
        - name: usedmarket-backend
          image: 371293081109.dkr.ecr.ap-northeast-2.amazonaws.com/usedmarket-backend:latest
          ports:
            - containerPort: 8080

          # 리소스 (EC2 t3.medium 기준 안정적인 수준)
          resources:
            limits:
              cpu: "1"        # 최대 1 vCPU
              memory: "1Gi"   # 최대 1GB
            requests:
              cpu: "0.3"      # 최소 0.3 vCPU
              memory: "512Mi" # 최소 512MB

          # Secret → environment mapping
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: DB_HOST

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: DB_USER

            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: DB_PW

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: JWT_SECRET

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: AWS_S3_BUCKET

            - name: AWS_S3_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: AWS_S3_BASE_URL

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: GOOGLE_CLIENT_SECRET

            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: KAKAO_CLIENT_ID

            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: usedmarket-backend-secret
                  key: KAKAO_CLIENT_SECRET

          # 헬스체크 (준비 상태 확인 → 트래픽 받을 준비 됐는지)
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: usedmarket-backend-service
  namespace: suho
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: usedmarket-backend
