name: Deploy UsedMarket Backend

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github 
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster information 
        run: |
          aws eks update-kubeconfig \
          --name my-cluster \
          --region ap-northeast-2

      - name: Login to ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker image to ecr
        env:
          REGISTRY: 371293081109.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: usedmarket-backend
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./k8s/k8s-usedmarket/backend_depl_svc.yml
          kubectl rollout restart deployment usedmarket-backend -n suho
